<?php
/**
 * DCW Engage - Applicant Name Resolver
 *
 * Form field names are dynamically generated from question labels by the
 * form builder (e.g. 'Name and age' becomes 'name_and_age', 'Applicant Name'
 * becomes 'applicant_name').
 *
 * This helper resolves the real applicant name across diverse builder-generated
 * field names, avoiding the generic 'Applicant' fallback while safely ignoring
 * non-applicant fields like organization_name or project_name.
 */

function resolveApplicantName(array $postData, array $schema = [], string $fallback = 'Applicant'): string
{
    // 1. Check prioritized exact field keys commonly generated by the builder
    $preferredKeys = [
        'full_name',
        'applicant_name',
        'name_and_age',
        'name_age',
        'your_name',
        'candidate_name',
        'legal_name',
        'name',
    ];

    foreach ($preferredKeys as $key) {
        if (isset($postData[$key]) && is_scalar($postData[$key])) {
            $value = trim((string) $postData[$key]);
            if ($value !== '' && mb_strlen($value) <= 120) {
                return $value;
            }
        }
    }

    // 2. If a form schema is provided, inspect text fields by label and name
    foreach ($schema['fields'] ?? [] as $field) {
        // Skip non-text fields (e.g. file uploads, textareas, dropdowns, checkboxes)
        if (!empty($field['type']) && !in_array($field['type'], ['text', ''], true)) {
            continue;
        }

        $fieldName = trim((string) ($field['name'] ?? ''));
        $fieldLabel = trim((string) ($field['label'] ?? ''));
        if ($fieldName === '') {
            continue;
        }

        $normalizedName = strtolower($fieldName);
        $normalizedLabel = strtolower($fieldLabel);

        // Guard against non-applicant fields (e.g. organization_name, project_name)
        if (preg_match('/(org|institution|company|project|event|workshop|chapter|group|domain|user|file|school|college|bank|father|mother|guardian)/', $normalizedName)
            || preg_match('/(org|institution|company|project|event|workshop|chapter|group|domain|user|file|school|college|bank|father|mother|guardian)/', $normalizedLabel)) {
            continue;
        }

        $looksLikeName = (bool) (
            preg_match('/^(full_?name|applicant_?s?_?name|your_?name|candidate_?name|legal_?name|name)(_|$)/', $normalizedName)
            || preg_match('/^name_?(and_?|&_?)?age(_|$)/', $normalizedName)
            || preg_match('/^(full\s+name|applicant(\'s)?\s+name|your\s+name|candidate\s+name|legal\s+name|name)(\s+|$)/', $normalizedLabel)
            || preg_match('/^name\s*(&|and)\s*age/', $normalizedLabel)
        );

        if ($looksLikeName && isset($postData[$fieldName]) && is_scalar($postData[$fieldName])) {
            $value = trim((string) $postData[$fieldName]);
            if ($value !== '' && mb_strlen($value) <= 120) {
                return $value;
            }
        }
    }

    // 3. Fallback scan of submitted keys if schema is unavailable or field was custom
    foreach ($postData as $key => $val) {
        if (!is_scalar($val)) {
            continue;
        }

        $normalizedKey = strtolower((string) $key);
        if (preg_match('/(org|institution|company|project|event|workshop|chapter|group|domain|user|file|school|college|bank|father|mother|guardian)/', $normalizedKey)) {
            continue;
        }

        if (preg_match('/^(full_?name|applicant_?s?_?name|your_?name|candidate_?name|legal_?name)(_|$)/', $normalizedKey)
            || preg_match('/^name_?(and_?|&_?)?age(_|$)/', $normalizedKey)) {
            $value = trim((string) $val);
            if ($value !== '' && mb_strlen($value) <= 120) {
                return $value;
            }
        }
    }

    return $fallback;
}
